In [13]:
# Question-1  ARRAYS

import numpy as np

arr = np.array([1,2,3,4,9,6],float)
arr[::-1]

array([6., 9., 4., 3., 2., 1.])

In [29]:
# Question-2 numpy array shape

print(np.array(input().split(), int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
# Question-3 transpose matrix and flatten matrix

arr = (np.array(input("give any 4 numbers in input with space:").split(), int)).reshape(int(input("give number of rows:")),int(input("give number of columns:")))
print(np.transpose(arr))
print(arr.flatten())

give any 4 numbers in input with space: 1 2 3 4
give number of rows:2 
give number of columns:2
[[1 3]
 [2 4]]
[1 2 3 4]


In [3]:
# Question- 4 Concatenate

import numpy as np
n, m = map(int,input().split())
arrA = np.array([input().split() for i in range(n)],int)
arrB = np.array([input().split() for i in range(m)],int)
print(np.concatenate((arrA, arrB), axis = 0))

1 2 3
2 3 
 3 5 
 4 5
[[2 3]
 [3 5]
 [4 5]]


In [16]:
#Question-5 Zeros and Ones

print(np.zeros((3,3,3), dtype=int)) 
print(np.ones((3,3,3), dtype=int))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [18]:
# Question-6 Identity matrix

np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
# Question-7 Array Mathematics


import numpy as np

n = int(input("give number of rows:"))
m = int(input("give number of columns:"))
a = np.array(input("give input of some numbers with space separated:").split(),int)
b = np.array(input("give input of some numbers with space separated:").split(),int)

print("addition of arrays:",(np.array(a+b).reshape(n,m)))
print("subtraction of arrays:",(np.array(a-b).reshape(n,m)))
print("division of arrays:",(np.array(a//b).reshape(n,m)))
print("multiplication of arrays:",(np.array(a*b).reshape(n,m)))
print("power of arrays:",(np.array(a**b).reshape(n,m)))
print("mod of arrays",(np.array(a%b).reshape(n,m)))

give number of rows:1
give number of columns:3
give input of some numbers with space separated:1 2 3
give input of some numbers with space separated:4 5 6 
addition of arrays: [[5 7 9]]
subtraction of arrays: [[-3 -3 -3]]
division of arrays: [[0 0 0]]
multiplication of arrays: [[ 4 10 18]]
power of arrays: [[  1  32 729]]
mod of arrays [[1 2 3]]


In [11]:
# Question-8 Ceil, FLoor, Rint of array elements

a = np.array(input().split(), float)

print(np.ceil(a))
print(np.floor(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [27]:
# Question-9 sum and product of arrays

n = int(input())
m = int(input())

s = np.array(input().split(), int).reshape(n,m)
d = np.sum(s,axis=0)
print("sum of array:",d)

g = np.prod(d, axis=0)
print("prod of sum of array:",g)

2 
2 
1 2 3 4
sum of array: [4 6]
prod of sum of array: 24


In [46]:
# Question-10 min and max of arrays

n = int(input("no. of rows:"))
m = int(input("no.columns:"))

s = np.array(input().split(), int).reshape(n,m)
print(s)
print("min of arrary:",np.min(s, axis=0))
print("max of array:",np.max(s, axis=0))

no. of rows:4
no.columns:2
85 65 42 75 12 43 58 4
[[85 65]
 [42 75]
 [12 43]
 [58  4]]
min of arrary: [12  4]
max of array: [85 75]


In [53]:
# Question-11 dot product

n = int(input())

a = np.array(input().split(), int).reshape(n,n)
print("s matrix:",a)

b = np.array(input().split(), int).reshape(n,n)
print("b matrix:",b)

print("dot product:",np.dot(a,b))

2
1 2 3 4
s matrix: [[1 2]
 [3 4]]
1 2 3 4
b matrix: [[1 2]
 [3 4]]
dot product: [[ 7 10]
 [15 22]]


In [55]:
# Question-12 mean, variance, standard deviation

n = int(input("no. of rows:"))
m = int(input("no.columns:"))

s = np.array(input("give numbers of given matrix size:").split(), int).reshape(n,m)
print(s)
print("mean of arrary:",np.mean(s, axis=1))
print("var of array:",np.var(s, axis=0))
print("std of array:",np.std(s, axis=None))

no. of rows:2
no.columns:2
give numbers of given matrix size:1 2 3 4
[[1 2]
 [3 4]]
mean of arrary: [1.5 3.5]
var of array: [1. 1.]
std of array: 1.118033988749895


In [63]:
# Question-13 inner and outer

a = np.array(input().split(),int).reshape(1,2)
b = np.array(input().split(),int).reshape(1,2)

print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
[[3]]
[[0 0]
 [2 3]]


In [78]:
# Question-14 polynomial

print (np.polyval(list(map(float,input().split())), float(input())))

1.1 2 3
0
3.0


In [92]:
# Question-15 Determinant

n = int(input("no. of rows and columns:"))

s = np.array(input("give numbers of given matrix size:").split(), float).reshape(n,n)
print(s)
print("det of arrary:",np.linalg.det(s))

no. of rows and columns:2
give numbers of given matrix size:1.1 1.1 1.1 1.1
[[1.1 1.1]
 [1.1 1.1]]
det of arrary: 0.0
